[app]
name = "Select Avatars"
category = "Badge"
menu = "Badge"
#wifi_preference = false

[entry]
class = "DisplayAvatar"

[metadata]
author = "Camopants"
license = "LGPL-3.0-only"
url = "https://codeberg.org/camopants/tildagon-display-avatar"
description = "A simple application to display a selection of avatars in rotation. See README.MD at https://codeberg.org/camopants/tildagon-display-avatar/src/branch/main/README.md"
version = "4.0"
