[app]
name = "Select Avatars"
category = "Badge"
menu = "Badge"
#wifi_preference = false

[entry]
class = "DisplayAvatar"

[metadata]
author = "Camopants"
license = "LGPL-3.0-only"
url = "https://codeberg.org/camopants/tildagon-display-avatar"
description = "Display a selection of avatars, selecting with UP and DOWN buttons. Upload additional avatars with mpremote."
version = "4.0"
